
export const scrapedData = [
  { name: 'billyBobJones', hobbies: 'eating' },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
  { name: '', 
    email:'',
    company:'',
    job: '',
    linkedIn: '',
    instagram: ''
  },
];